apiVersion: v1
kind: Service
metadata:
  name: {{ include "azure-sql-edge-mock.fullname" . }}
  labels:
    app: {{ include "azure-sql-edge-mock.fullname" . }}
spec:
  ports:
  - port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    app: {{ include "azure-sql-edge-mock.fullname" . }}
  type: ClusterIP
